#!/usr/bin/env bash
#install ngx

sudo apt-get -y update
sudo apt-get -y install nginx
chmod u+x /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart