#!/usr/bin/env bash
#this script displays infos from the /etc/passwd file
file="/etc/passwd"
while  IFS=: read -r us_name pwd us_id gp_id us_inf hm cmd
do
echo "The user $us_name is part of the $gp_id gang, lives in $hm and rides $cmd. $us_id's place is protected by the passcode $pwd, more info about the user here: $us_inf"
done < /etc/passwd
