#!/usr/bin/env bash
# print good and bad luck  in specific position
count=0
while [ $count -le 9 ]
do
((count++))
if [ $count -eq 4 ]
then
echo "bad luck"
elif [ $count -eq 8 ]
then
echo "good luck"
else
echo "Holberton School"
fi
done
