#!/usr/bin/env bash
# print bad luck and good luck
count=0
while [ $count -le 19 ]
do
count=$((count+1))
echo "$count"
case $count in
17)
echo "bad luck from Italy" ;;
9)
echo "bad luck from Japan" ;;
4)
echo "bad luck from China" ;;
esac
done
