#!/usr/bin/env bash
# print the hours and minute
count_h=0
count_m=0
while [ $count_h -le 11 ]
do
count_h=$((count_h+1))
echo "Hour: $count_h"
while [ $count_m -le 59 ]
do
echo "$count_m"
((count_m++))
done
count_m=1
done
