#!/usr/bin/env bash
# anu description for port 8080
sudo pkill -f apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart