#!/usr/bin/env bash
#fix 2 v2
sudo pkill -f apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 666 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
